cityofaustin/austinconventioncenter.com

README.md
_config.yml

The README provides a quick explanation the project to anyone who
might find it on a GitHub, and more in-depth usage instructions to
developers working on the project.
I decided while writing it to add \_data/contentful to the .gitignore,
instead of committing the YAML files it contains to master; that
change has since been committed to master. My thinking is that
committing changes to the data file in our topic branches could easily
become noisy and distracting, and even potentially introduce
cumbersome merge conflicts. The downside to _not_ committing it is
that every developer on the project currently needs Contentful API
keys to sync the updated data; especially once the data stabilizes
(i.e. by the time the new website launches), that might not be ideal.
At that point, our continuous …

Add README, including Contentful-related developer usage docs

---

circle.yml

The `s3_website push` deploy command automatically downloads the .jar
file that does s3_website's heavy lifting, but the download is not
cached by Circle. This is a workaround to download the file during
the build's dependency phase, so that it'll be cached.
It's obviously a made somewhat fragile by being contigent on
s3_website's internals (https://github.com/laurilehmijoki/s3_website/blob/v2.15.1/bin/s3_website#L200-L245),
so I might open an issue on s3_website suggesting the addition of an
`s3_website download` or similar command that we could use instead.

Configure Circle to download s3_website.jar during dependency phase

---

Gemfile
Gemfile.lock
_plugins/filters/format_phone.rb

Uses ActiveSupport's [number_to_phone][] helper.
`{{ "5555555555" | format_phone }}`
[number_to_phone]: http://api.rubyonrails.org/classes/ActiveSupport/NumberHelper.html#method-i-number_to_phone

Add format_phone Liquid filter

---

_includes/components/breadcrumbs.html
_includes/footer.html
_includes/header.html
_plugins/tags/url_for.rb

Menus (or any Contentful objects that reference arbtirary sections
and pages) can't always know or guess the full URL of each of their
documents, so url_for provides a way to match a given Contentful ID
to an existing Document and return its URL. Named after the Rails
helper, but way less fancy.

Create a url_for tag to match Contentful objects to document URLs

---

Gemfile
Gemfile.lock
_config.yml
_plugins/generators/contentful.rb

Pages and Sections now include a redirectFrom attribute to specify
paths that should be redirected (such as /directions/floors.htm to
/facilities/plans/). Input is validated on the Contentful side and
set as the data attribute expected by jekyll-redirect-from.
https://github.com/jekyll/jekyll-redirect-from

Allow redirects to be specified in Contentful data

---

_config.yml
_custom/sections/press-releases.html
_layouts/press_release.html
_plugins/generators/contentful.rb

Each press release now renders as a page using the press_release
layout and blog-like URL that includes the date. They're added to a
press-releases collection corresponding to the Contentful section,
the index page of which  is rendered from _custom, much like the new
Calendar index. I still don't love _custom for this, but it works for
now.
Press release archive pages (by year) are not yet implemented but will
be added later.

Render press releases

---

_plugins/generators/calendar.rb

Generally nice to minimize blocking dependencies in dev, but I think
this is a sensible default even for production builds.

Prevent jekyll build failure in the absence of calendar data

---

_assets/javascripts/main.js
_config.yml
_includes/components/content_blocks.html
_includes/components/content_blocks/accordion.html
_includes/components/content_blocks/text.html
_layouts/default.html
_layouts/page.html

This adds support for a new content block type, accordionBlocks, which
is intended to group text blocks into [USWDS accordion lists][uswds].
The accordion component depends on USWDS JS, which is now required in
a main.js included in the default layout. Unlike USWDS Sass, which
we're bundling from source, this includes the bundled/minified JS,
because our build process doesn't currently support commonJS modules.
[uswds]: https://standards.usa.gov/accordions/

Template accordion content blocks

---

Rakefile
_assets/javascripts/main.js
_assets/javascripts/photoswipe.js
_assets/stylesheets/components/gallery.scss
_assets/stylesheets/main.scss
_assets/stylesheets/vendor/photoswipe.scss
_config.yml
_includes/components/content_blocks.html
_includes/components/content_blocks/gallery.html
_includes/components/photoswipe.html
_plugins/mappers/gallery_block_mapper.rb
package.json

Gallery blocks now render as responsive grid of thumbnails cropped to
a 3:2 aspect ratio, and display in full (also responsive) sizes in
PhotoSwipe (photoswipe.com).
I picked PhotoSwipe from GitHub, where (by my estimation) it's the
most popular JS image viewer by far (12k+ stars). It has solid
documentation and an active community, and fairly extensive options
for customizing both the appearance and behavior. It's completely
markup-agnostic, which means we can use Schema.org's ImageGallery
markup.
The new JS file here is based on PhotoSwipe's example code, but
it doesn't bother with IE8 compatability and has a couple notable
differences:
* The responsive image sizing uses Contentful's Images API. Since
PhotoSwipe needs the dimensions among its options, we calculate
them based on the …

Implement responsive image gallery and viewer (PhotoSwipe)

---

_assets/stylesheets/components/gallery.scss

1. Safari doesn't play nicely with max-width (see
[philipwalton/flexbugs #11]), so this switches to width.
2. Firefox doesn't render percentage bottom-margins on flex items,
which is apparently not a bug but the correct behavior, so this
switches to ems for the margins, and consequently calc for the
widths.
Haven't yet tested this layout in IE so more fun may be yet to come.
[philipwalton/flexbugs #11]: https://github.com/philipwalton/flexbugs#11-min-and-max-size-declarations-are-ignored-when-wrapping-flex-items

Fix Flexbox-related bugs affecting Safari and Firefox

---

_includes/components/sidebar_blocks/contact.html

Sidebar contact blocks attempt to infer a division contact page from
the Division contact attribute (which comes from a set predefined in
Contentful); this simply makes it so that we don't generate a broken
link if the page doesn't exist.

Ensure a division contact page exists before linking to it

---

_layouts/press_release.html
_plugins/generators/contentful.rb

Since the titles tend to be very long.

Force press release page breadcrumb to show date instead of title

---

_assets/images/floor-plan-overview.svg
_assets/javascripts/floor_plan.js
_assets/stylesheets/components/floor_plans.scss
_assets/stylesheets/main.scss
_assets/stylesheets/vendor/tooltip.scss
_layouts/floor_plan.html
_templates/facilities/plans.html
package.json

The floor plan maps now show a tooltip w/ the room name over each
room on over, and add a hover state and click handling if a matching
page is found in the floor plan sidenav.
* I couldn't find much documentation of this, but Chrome and Safari
seem to disallow reading an externally-hosted SVG embedded with an
<object> tag, throwing a same-origin error despite CORS headers. So
instead of <object> tags, the level SVGs are now just pasted into
the corresponding textBlocks. Not ideal, maybe, but unlike directly
adding the SVGs here, it means we don't have to maintain a room-to-
level mapping, since the page-to-text-block relationship is kept by
Contentful.
* Embedding the SVG directly seems like it might also provide an
advantage over <object> in terms of interoperability with third-
party JS …

Convert floor plan maps to interactive SVGs

---

_layouts/section.html
_plugins/generators/contentful.rb

Priority is set as a number in Contentful (lower number = higher
sort). Pages without a priority sort last.

Sort section pages list by priority attribute

---

_assets/stylesheets/components/floor_plans.scss

The definition-list approach to marking up the room configuration
ended up being not very semantic, so this now simply expects an
unordered list of class `acc-room-configurations` to contain list
items of class `acc-room-configuration`. Kramdown will render Markdown
inside each item given a `markdown="1"` attribute on the `<li>` tag, so
the editor's version is still pretty clean. For example:
```
<ul class="acc-room-configurations"><li markdown="1" class="acc-room-configuration acc-banquet">
66" rounds: 2,000 guests \\
72" rounds: 1,430 guests
</li></ul>
```
I suspect we may want to abstract the flexbox-list classes (or create
a mixin) so that they can be used elsewhere (e.g. room
specifications), but for now they're just added to the room
configuration classes.

Update floor plan styles to render a setups list as flexbox grid

---

_assets/stylesheets/components/floor_plans.scss
_assets/stylesheets/components/header.scss
_assets/stylesheets/components/sidebar.scss
_assets/stylesheets/elements/buttons.scss
_assets/stylesheets/elements/typography.scss
_assets/stylesheets/variables/all.scss
_assets/stylesheets/variables/uswds.scss
_layouts/floor_plan.html
_layouts/page.html
_layouts/section.html

Removes some of the $acc- variables that weren't widely used, and
moves toward using USWDS variables instead of overriding tag styles
(such as for the header fonts).
I've also moved the page-title H1s, which were children of `usa-
grid`, into `usa-width-one-whole` within the page's main `usa-grid`,
and then within semantic `<header>` tags, so the H1 margins are no
longer removed by grid-related first-child/last-child rules.

Match color and type styles to latest specs

---

Gemfile
Gemfile.lock
_assets/stylesheets/components/footer.scss
_assets/stylesheets/main.scss
_assets/stylesheets/vendor/font_awesome.scss
_includes/footer.html

Also adds Font Awesome to the asset pipeline, and uses it for the
Facebook and Instagram links in the footer; it will also replace SVGs
for the majority of other icons on the site, per the design spec.

Match footer styles to spec and improve responsive spacing

---

_assets/stylesheets/components/breadcrumbs.scss
_includes/components/breadcrumbs.html

* The breadcrumb bar is now slightly shorter on desktop (6rem rather
than 7) and shorter still on mobile (4rem).
* The current page's breadcrumb is now a span, rather than a
clickable link.
* The breadcrumb partial now adds an acc-breadcrumb-mobile class to
the breadcrumb we want to display on small screens: either the
current page, if it doesn't have a parent, or the link to the
parent, if it does. The latter is styled on mobile with a back
arrow. (The SVG for the arrow needs to be updated—it currently
points the wrong way and is the wrong color.)

Match breadcrumb style to spec and add mobile styles

---

_assets/stylesheets/components/breadcrumbs.scss
_includes/components/breadcrumbs.html

* Switches from float to flexbox to prevent wrapping in the event of
having too many breadcrumbs to fit horizontally, but also changes
the mobile breakpoint to the more conservative $nav-width, which
makes the too-many case much less likely.
* Corrects the left-padding of the mobile breadcrumb when it's not
the first child.

Fix a couple breadcrumb display bugs

---

_assets/javascripts/components/nav.js
_assets/javascripts/main.js
_assets/stylesheets/components/header.scss
_assets/stylesheets/main.scss
_assets/stylesheets/vendor/hamburgers.scss
_includes/header.html
package.json

Replaces the USWDS navigation component with custom styles, a
flexbox-based header layout, and a drawer that slides vertically
below the header on small screens, rather than a full-height right-
hand sliding panel.
The new menu button uses a hamburger-to-close component from Jonathan
Suh's [hamburgers] library (installed via npm).
[hamburgers]: https://github.com/jonsuh/hamburgers

Switch responsive primary navigation to hamburger/slideout pattern

---

_includes/footer.html
index.html

Jekyll's Liquid where filter has an odd bug that prevents it from
correctly matching values with spaces in the name, so this switches
to where_exp so that we can have values with spaces.

Rename menus with spaces, working around Jekyll where filter bug

---

_assets/javascripts/photoswipe.js
_assets/stylesheets/components/gallery.scss
_includes/components/content_blocks/gallery.html

Instead of thumbnails that open an image viewer. This lets content
editors use gallery blocks when they only need to add one or two
images to a page, which is preferable to using a text block because
it means the asset can be replaced in Contentful without needing to
also edit the text blocks that reference it.

Support option to render gallery as full-width images

---

404.html
_assets/stylesheets/components/calendar.scss
_assets/stylesheets/print.scss
_includes/head.html
_layouts/calendar.html
_layouts/floor_plan.html
_layouts/page.html
_layouts/section.html
_templates/press-releases.html

* Hides all content not in #main-content
* Displays all accordion content and optimizes "accordion button"
styles
* Improves calendar rendering in print
* Adds a "Please consider the environment" note to the top of the
first printed page
* Adds a "acc-content-header" class to the header tags containing the
page title, so that it can be targeted and prefixed with the site
title in print.

Create basic print stylesheet

---

_assets/stylesheets/elements/buttons.scss
_assets/stylesheets/elements/forms.scss
_assets/stylesheets/main.scss
_assets/stylesheets/variables/uswds.scss
_assets/stylesheets/vendor/uswds.scss
_config/acc.yml
_config/pec.yml
_layouts/page.html
_templates/book-an-event.html

* Uses and mostly doesn't modify the USWDS form styles. Implements
semantic types (email, date) and attributes (required) to maximize
browser-specific form features (like Chrome's validation and date
picker).
* The form is relayed to email via FormSpree, to an email address
specificied in the site-specific YAML config files. The main caveat
with FormSpree is that it requires confirming the domain/email pair
each time either changes, e.g. separately on the beta and www
subdomains and separately for ACC and PEC.
* FormSpree redirects to the URL specified in the hidden input named
next, which is currently set to "/thank-you/", so that page must be
created and maintained in Contentful.

Add Contact Sales form to the Book an Event page template

---

Gemfile
Gemfile.lock
README.md
Rakefile

Intended as the simplest possible way to trigger a rebuild of the
both sites each night, which needs to happen to ensure the Calendar
stays up-to-date even if updates aren't made via GitHub or Contentful
in the current month.
It's obviously a somewhat naive solution, but the risks of failure
are fairly low, and low-cost even if they do happen. As the City
invests resources in building out more static-site infrastructure,
it's possible (even probable) that this will be replaced by something
a little more robust (e.g. with error handling, and perhaps using
Lambda w/ Cloudwatch events instead of Heroku Scheduler).

Add a simple rake task to trigger nightly site rebuilds via Heroku

---

_config/pec.yml
_includes/analytics/facebook_analytics.html
_includes/head.html

This includes 2 levels of FB campaign tracking - a page view and what I believe is a paid campaign referral tracking that is isolated to the "Book an Event" page. I was not able to confirm the efficacy of the tracking snippet due to lack of access to the associated FB ads campaign. I am assuming that I can daisy-chain the `PageView` and `Lead` functions within a single `<script>` tag but without access to the campaign itself I cannot confirm this.

Add Facebook campaign analytics

---

_layouts/calendar.html

Some calendar links work and others are broken. This is because "http://" is being prepended to all links, but in the data, some links already have the "http://" or "https://" included.
This change checks the event.website to determine if http or https is included and 
only adds it when it is missing (as required for our application to recognize that is is 
a full URL and not a relative one). 
In the 2018 calendar and production, the following links on production are broken:
2018 American Meterological Society
2018 SXSW Volunteer Call
2018 Virtual Reality Show
2018 Build Expo
2018 Dell Children's Gala
2018 SXSW Volunteer call
2018 TASA Midwinter Conference
The fix for this is already deployed on staging and can be tested on those pages there. 
As an additional note, the last link (TASA …

fix links for calendar

---

_config.yml
_layouts/events.html
_plugins/generators/calendar.rb
_templates/calendar.html
_templates/events.html
lib/calendar/import.rb

The primary goal was for the "Calendar" page/section to be renamed "Events" on the user-facing parts of the site. The change could have been isolated more than it is here, only making the substitution where the calendar builder is looking for the "Events" content item from Contentful, but then we would have been left with routes that say "/calendar" for a top-level page titled "Events", and the code that supports this feature would have been semantically inconsistent, and therefore confusing. This resulted in my decision to replace all references to "Calendar". The one place this gets weird is in the nesting of individual "events" under the "events" parent list (instead of "events" being children under "calendar" but) but I felt like that was a more reasonable approach than turning …

Rename "Calendar" as "Events"

---

_layouts/events.html

I initially tried doing this via Contentful, but ran into complexity in the site build process since all of the events/calendar pages are currently generated purely with Socrata data. To add a relationship between the contentful data and the events page within the build process seemed like far more effort than it was worth to make a couple pieces of static text that are not likely to change more than 2x/year editable via Contentful.
[Trello card](https://trello.com/c/8E0tlccS/323-include-disclaimer-verbiage-above-the-events-calendar-on-staging)

Add disclaimer to events page

---

_assets/javascripts/click_tracking.js

The decision was made to use Ungerboeck's white-label form creator to create temporary RFP forms until we have a native solution for website-to-USI RFP submission in place. Accordingly, the RFP text block in contentful has been updated to provide a link to the form instead of a solictation to email the sales team. This analytics change removes the old form submission tracking and replaces it with click tracking on the new RFP link, which is used on both the ACC and PEC sites.

Track clicks on RFP external link clicks

---

_config/pec.yml
_config/pec_staging.yml
_layouts/events.html

This text is being added with the goal of reducing the number of event-specific inbound queries that come through via email and phone.

Add disclaimer text to Events page

---

_config/acc.yml
_config/pec.yml

During the last undertaking around Analytics and, specifically, Event Tracking, I realized that Events triggered in local development were resulting in Event logs for the Production sites, despite not occurring on the production URLs specified in the GA profiles. Rather than continue to use the same GA profiles with knowingly-invalid data we (Me, Leslie Barrientos, Chris Hernandez) decided it would make sense to just create a fresh profile so we know all the data is valid.
The old profiles still exist, they just won't be collecting data anymore.

Change Google Analytics profiles for production sites

---

_layouts/press_release.html

With the COVID-19 impact on Convention Center business there's a need to have more flexibility with follow-up contact information for certain press releases. This change is intended to allow the marketing department to provide more tailored follow-up information on a release-by-release basis.

Remove hard-coded contact info from Press Releases

---

.circleci/config.yml

No more need for Heroku Scheduler now that CircleCI has workflows with CRON scheduling built in! This builds the site every hour, on the :15. CircleCI may shift this time by up to 10 minutes depending on request load at the scheduled time so it should not be treated as exact.

Automate hourly production builds on CircleCI

---

_assets/stylesheets/elements/press_release.scss
_assets/stylesheets/main.scss
_layouts/press_release.html
_plugins/generators/contentful.rb
_templates/press-room.html

This provides a balance of greater styling with easier ability for content managers to select from a pre-determined list of "For More Information" contact resources. The standard approach is to use ACCD information, but for COVID-19 releases this also adds the option to list the CoA Communications office _instead_. This list can always be expanded or contracted based on the need of the day.

Add support for Contentful-driven press contact

---

_assets/javascripts/main.js
_assets/javascripts/meet_the_team.js
_assets/stylesheets/components/nav.scss
_assets/stylesheets/elements/meet_the_team.scss
_assets/stylesheets/main.scss
_config.yml
_plugins/generators/contentful.rb
_templates/in-the-news.html
_templates/meet-the-team.html
_templates/press-releases.html

A Newsroom navigation item has been added to provide greater flexibility around corporate communications/messaging. The initial release includes Press Releases (formerly Newsroom, formerly Press Room, formerly Press Releases) and a new "In The News" section, for 3rd-party articles/media written _about_ ACCD instead of _by_ ACCD.
Future Newsroom pages will include Expansion Plans and likely some contact/Meet The Team stuff.
This required additions and edits to the Contentful Content Models.

Introduce "Newsroom" nav construct

---

.circleci/config.yml

Now that the new subsections (especially Meet The Team) are in-place the Content Model is no longer undergoing breaking changes.

Re-add auto-deploy

---

.circleci/config.yml

Content managers are now able to use their CoA AzureAD credentials to access the web admin dashboard, allowing us to free up these auto-build resources while reducing almost all friction around manual deployments.

Remove scheduled builds from CircleCI config

---

index.html

The original implementation of the homepage video mega feature was limited to just the ACC site, but now that the PEC video has been produced we'll use the feature on both sites. For now it's still hard-coded until we have a discussion around a proper video feature spec. Until then, one-off updates for one-off tasks until a pattern emerges.
The marketing team also requested that the current Mega Feature photo gallery teaser be removed from PEC, at least temporarily, hence the conditional logic there. The Mega Feature Content Item has been unpublished and removed from the Homepage Content Blocks in Contentful, but remains intact and configured to be re-introduced any time in the future.

Update PEC homepage elements

---

_assets/stylesheets/elements/meet_the_team.scss
_templates/meet-the-team.html

This change allows a content editor in Contentful to add a team image as a File on the Meet The Team page. If this file is present, the template will render that image full-width between the page banner and executive bios.

Add support for team photo on Meet The Team page
